/**
 * 자막 두 벌. 숫자는 전부 D 에서 끼워 넣는다 — 문구에 숫자를 직접 쓰지 않는다.
 */
import { D, fmt, money, type Lang } from './data';

const c = D.counts;
const tl = D.timeline;
const top = D.topCosponsor;

/** 한국어 조사 — 이름 끝 글자의 받침으로 고른다 (워런이 / 콜린스가) */
const josa = (word: string, withBatchim: string, without: string) => {
  const code = word.charCodeAt(word.length - 1) - 0xac00;
  const has = code >= 0 && code <= 11171 && code % 28 !== 0;
  return word + (has ? withBatchim : without);
};

export const COPY = {
  en: {
    introKicker: `${c.figures} figures in American politics`,
    allied: 'Who’s allied.',
    feuding: 'Who’s feuding.',
    hubLine: (n: number) => `One person touches ${n} of ${c.curated} relationships.`,
    removeHub: 'Remove the hub.',
    pieces: 'pieces',
    piecesSub: `It was ${D.hub.componentsBefore} before. The core keeps ${D.hub.largestAfter} of ${c.figures - 1}.`,
    notBlocs: 'Not two blocs — a hub-and-spoke network.',
    tagline: 'U.S. Politician Relationship Atlas',
    stats: [
      [c.figures, 'figures'],
      [c.curated, 'curated ties'],
      [c.cosponsorFresh, 'measured edges'],
      [c.signals, 'news signals'],
    ] as [number, string][],
    uiGraph: 'Every edge is a documented relationship.',
    uiGraphSub: '2D canvas · 3D WebGL',
    ui3d: 'Rotate it in three dimensions.',
    uiLegend: 'The legend is the filter.',
    uiLegendSub: 'Switch off a tie type — whoever is left without one dims.',
    tlTitle: 'Watch a relationship flip.',
    tlNames: `${tl.a.en} × ${tl.b.en}`,
    tlFlips: { '2025-06': 'Public breakup', '2026-01': 'Mar-a-Lago reconciliation' } as Record<string, string>,
    tlRules: ['One vote per pair, per day', 'A flip needs a 2 : 1 margin', 'Split months are hatched, not recoloured'],
    legendAlly: 'Alliance',
    legendFeud: 'Feud',
    legendNeutral: 'Neutral',
    wireTitle: 'Every night, it reads the political press.',
    wireSub: 'An LLM judges each headline — ally, feud, or neutral.',
    wireCount: 'signals in a rolling one-year archive',
    wireJudged: (n: number) => `${fmt(n)} judged`,
    wireUnjudged: (n: number) => `${fmt(n)} unjudged — and labelled that way`,
    cosTitle: 'Measured, not curated.',
    cosSub: `${c.cosponsorFresh} edges from ${fmt(c.billsScanned)} bills of the 119th Congress.`,
    cosDashed: 'Drawn dashed, so a measurement is never mistaken for an editorial claim.',
    cosPair: `${top.a.en} × ${top.b.en}`,
    cosBills: `${top.bills} bills together`,
    cosDir: `${top.b.en} signed ${top.byA} of ${top.a.en}’s · ${top.a.en} signed ${top.byB} back`,
    infTitle: 'Influence lives on the profile — not on the graph.',
    money: 'Campaign money',
    moneyRows: [
      ['PAC → candidate', D.funding.pacDirect, 'direct'],
      ['Outside spending FOR', D.funding.ieSupport, 'for'],
      ['Outside spending AGAINST', D.funding.ieOppose, 'against'],
    ] as [string, number, string][],
    moneyNote: `${money(D.funding.massie.oppose)} was spent against ${D.funding.massie.name.en}. Add it up naively and it looks like backing.`,
    lobby: 'Revolving door',
    lobbyLine: `former staffers of ${D.lobbying.people} figures now registered as lobbyists`,
    defect: 'Party-line defection',
    defectLine: `${D.unity.collins.name.en} votes against her party on`,
    defectTail: `of ${fmt(D.unity.partyVotes)} party-divided votes`,
    infFoot: 'Each number says what it does NOT mean.',
    trustTitle: 'Every tie shows its sources —',
    trustSub: 'or says plainly that it has none.',
    mixTitle: 'Where the news comes from is on screen.',
    mixSub: `Top 5 outlets carry ${D.mix.topShare}% — and polarity comes from the headline alone.`,
    langTitle: 'English · 한국어',
    langSub: 'Every label, every story, every LLM summary — in both.',
    endLine: 'Who’s allied. Who’s feuding. Who just flipped.',
    endUrl: 'world-politicians.vercel.app',
    endMeta: 'Free · Open source (MIT) · No signup · Refreshed nightly',
    credit: 'Music: “Hitman” by Kevin MacLeod (incompetech.com) · Licensed under CC BY 4.0',
  },
  ko: {
    introKicker: `미국 정치의 핵심 인물 ${c.figures}명`,
    allied: '누가 손을 잡고,',
    feuding: '누가 싸우는가.',
    hubLine: (n: number) => `관계 ${c.curated}개 중 ${n}개가 한 사람에게 닿는다.`,
    removeHub: '허브를 빼면',
    pieces: '조각',
    piecesSub: `빼기 전엔 ${D.hub.componentsBefore}조각. 남은 ${c.figures - 1}명 중 중심에 ${D.hub.largestAfter}명.`,
    notBlocs: '두 진영이 아니다 — 허브와 바큇살의 네트워크다.',
    tagline: '미국 정치인 관계 지도',
    stats: [
      [c.figures, '인물'],
      [c.curated, '큐레이션 관계'],
      [c.cosponsorFresh, '측정 엣지'],
      [c.signals, '뉴스 신호'],
    ] as [number, string][],
    uiGraph: '모든 선은 공개 보도로 확인된 관계다.',
    uiGraphSub: '2D 캔버스 · 3D WebGL',
    ui3d: '3차원으로 돌려 볼 수 있다.',
    uiLegend: '범례가 곧 필터다.',
    uiLegendSub: '관계 유형을 끄면, 남은 연결이 없는 인물은 흐려진다.',
    tlTitle: '관계가 뒤집히는 순간을 본다.',
    tlNames: `${tl.a.ko} × ${tl.b.ko}`,
    tlFlips: { '2025-06': '공개 결별', '2026-01': '마라라고 화해' } as Record<string, string>,
    tlRules: ['한 쌍에 하루 한 표', '뒤집히려면 2 : 1 이상', '매체가 갈린 달은 빗금으로'],
    legendAlly: '동맹',
    legendFeud: '갈등',
    legendNeutral: '중립',
    wireTitle: '매일 밤, 정치 기사를 읽는다.',
    wireSub: 'LLM 이 헤드라인마다 동맹·갈등·중립을 판정한다.',
    wireCount: '건의 신호, 1년치 누적 아카이브',
    wireJudged: (n: number) => `${fmt(n)}건 판정`,
    wireUnjudged: (n: number) => `${fmt(n)}건 미판정 — 숨기지 않고 표시한다`,
    cosTitle: '편집이 아니라 측정이다.',
    cosSub: `119대 의회 법안 ${fmt(c.billsScanned)}건에서 뽑은 공동발의 엣지 ${c.cosponsorFresh}개.`,
    cosDashed: '점선으로 따로 그린다 — 측정값이 편집 판단으로 보이지 않게.',
    cosPair: `${top.a.ko} × ${top.b.ko}`,
    cosBills: `함께 발의한 법안 ${top.bills}건`,
    cosDir: `${josa(top.b.ko, '이', '가')} ${top.a.ko}의 법안에 ${top.byA}번 · 반대로는 ${top.byB}번 서명`,
    infTitle: '영향력은 그래프가 아니라 프로필에 둔다.',
    money: '선거 자금',
    moneyRows: [
      ['PAC → 후보 직접 기부', D.funding.pacDirect, 'direct'],
      ['후보 지지 독립지출', D.funding.ieSupport, 'for'],
      ['후보 반대 독립지출', D.funding.ieOppose, 'against'],
    ] as [string, number, string][],
    moneyNote: `${josa(D.funding.massie.name.ko, '을', '를')} 공격하는 데 ${money(D.funding.massie.oppose)}. 그냥 합치면 후원금처럼 보인다.`,
    lobby: '회전문',
    lobbyLine: `${D.lobbying.people}명의 전직 보좌진이 지금 로비스트로 등록돼 있다`,
    defect: '당론 이탈률',
    defectLine: `${josa(D.unity.collins.name.ko, '이', '가')} 자기 당과 반대로 던진 비율`,
    defectTail: `정당 표결 ${fmt(D.unity.partyVotes)}건 기준`,
    infFoot: '모든 수치 옆에, 그 수치가 무엇이 아닌지를 적는다.',
    trustTitle: '모든 관계는 근거를 보여준다 —',
    trustSub: '근거가 없으면, 없다고 말한다.',
    mixTitle: '어느 매체에서 온 뉴스인지 화면에 그대로.',
    mixSub: `상위 5개 매체가 ${D.mix.topShare}% — 극성은 헤드라인만으로 판정했다고 함께 적는다.`,
    langTitle: 'English · 한국어',
    langSub: '모든 라벨, 모든 스토리, 모든 LLM 요약을 두 언어로.',
    endLine: '누가 손을 잡고, 누가 싸우고, 누가 돌아섰는가.',
    endUrl: 'world-politicians.vercel.app',
    endMeta: '무료 · 오픈소스(MIT) · 가입 없음 · 매일 밤 갱신',
    credit: 'Music: “Hitman” by Kevin MacLeod (incompetech.com) · Licensed under CC BY 4.0',
  },
};

export type Copy = (typeof COPY)['en'];
export const copyFor = (lang: Lang): Copy => COPY[lang];
